#!/usr/bin/env python3.1

import sys
if len(sys.argv) < 2:
	print ("Usage: dump_evchain.py pokemon_id")
	sys.exit(-1)

from pprint import pprint
import pokemon
pprint(pokemon.moves_from_pokemonid(sys.argv[1]))


