#!/usr/bin/env python3.1

import sys
if len(sys.argv) < 2:
	print ("Usage: dump_evchain.py pokemon_id")
	sys.exit(-1)

from pprint import pprint
import pokemon
pokemon_id = sys.argv[1]
evid = pokemon.evid_from_pokemonid(pokemon_id)
pprint(pokemon.moves_from_evid(evid))


